services:
  - type: web
    name: easyreach-be
    env: java
    rootDir: backend                # <- run build/start in backend/
    buildCommand: mvn -q -B -DskipTests package
    startCommand: java -Dserver.port=$PORT -jar target/*.jar
    envVars:
      - key: DB_URL
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: JWT_SECRET
        sync: false
