spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://dpg-d2ioktje5dus73b8gv9g-a.singapore-postgres.render.com:5432/easyreach_db
    username: easyreach_db_user
    password: ${DEV_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://dpg-d2ioktje5dus73b8gv9g-a:5432/easyreach_db
    username: easyreach_db_user
    password: ${PROD_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
