server:
  port: 8080

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

    # --- HikariCP tuning (all in milliseconds) ---
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000         # wait up to 30s for a conn
      validation-timeout: 5000
      max-lifetime: 1800000             # 30 min; keep lower than provider's hard kill (e.g. 55m)
      idle-timeout: 600000              # 10 min; trim idle conns
      keepalive-time: 300000            # ping every 5 min so proxies don’t kill idle conns

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate.jdbc.time_zone: Asia/Kolkata

  flyway:
    enabled: true

  jackson:
    time-zone: Asia/Kolkata
    default-property-inclusion: non_null

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

jwt:
  secret-base64: ${JWT_SECRET}
  access-token:
    ttl-minutes: 15
  refresh-token:
    ttl-days: 7

logging:
  level:
    org.springframework: info
